steps:
  # Download keystore from Cloud Storage
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'gs://${_BUCKET_NAME}/keystore.jks', 'app/keystore.jks']

  # Build the app
  - name: 'gcr.io/cloud-builders/gradle'
    args: ['build']
    env:
      - 'GRADLE_USER_HOME=/workspace/.gradle'
      - 'KEYSTORE_FILE=keystore.jks'
      - 'KEYSTORE_PASSWORD=${_KEYSTORE_PASSWORD}'
      - 'KEY_ALIAS=${_KEY_ALIAS}'
      - 'KEY_PASSWORD=${_KEY_PASSWORD}'

  # Run unit tests
  - name: 'gcr.io/cloud-builders/gradle'
    args: ['test']
    env:
      - 'GRADLE_USER_HOME=/workspace/.gradle'
      - 'KEYSTORE_FILE=keystore.jks'
      - 'KEYSTORE_PASSWORD=${_KEYSTORE_PASSWORD}'
      - 'KEY_ALIAS=${_KEY_ALIAS}'
      - 'KEY_PASSWORD=${_KEY_PASSWORD}'

  # Build debug APK
  - name: 'gcr.io/cloud-builders/gradle'
    args: ['assembleDebug']
    env:
      - 'GRADLE_USER_HOME=/workspace/.gradle'
      - 'KEYSTORE_FILE=keystore.jks'
      - 'KEYSTORE_PASSWORD=${_KEYSTORE_PASSWORD}'
      - 'KEY_ALIAS=${_KEY_ALIAS}'
      - 'KEY_PASSWORD=${_KEY_PASSWORD}'

  # Build release APK
  - name: 'gcr.io/cloud-builders/gradle'
    args: ['assembleRelease']
    env:
      - 'GRADLE_USER_HOME=/workspace/.gradle'
      - 'KEYSTORE_FILE=keystore.jks'
      - 'KEYSTORE_PASSWORD=${_KEYSTORE_PASSWORD}'
      - 'KEY_ALIAS=${_KEY_ALIAS}'
      - 'KEY_PASSWORD=${_KEY_PASSWORD}'

  # Upload APK to Cloud Storage
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'app/build/outputs/apk/release/app-release.apk', 'gs://${_BUCKET_NAME}/app-${_VERSION_NAME}.apk']

  # Clean up keystore
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['rm', 'app/keystore.jks']

artifacts:
  objects:
    location: 'gs://${_BUCKET_NAME}/'
    paths: ['app-${_VERSION_NAME}.apk']

substitutions:
  _BUCKET_NAME: poc-app-releases
  _VERSION_NAME: ${BUILD_ID}
  _KEYSTORE_PASSWORD: ${_KEYSTORE_PASSWORD}
  _KEY_ALIAS: ${_KEY_ALIAS}
  _KEY_PASSWORD: ${_KEY_PASSWORD}

options:
  logging: CLOUD_LOGGING_ONLY 