steps:
  # Download keystore from Cloud Storage
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'gs://poc-app-releases/keystore.jks', 'app/keystore.jks']

  # Debug: List workspace contents
  - name: 'ubuntu'
    args: ['bash', '-c', 'ls -la && pwd']

  # Debug: Check Gradle wrapper
  - name: 'ubuntu'
    args: ['bash', '-c', 'ls -la gradlew* && cat gradle/wrapper/gradle-wrapper.properties']

  # Build the app using Android container
  - name: 'docker.io/cirrusci/android-sdk:34'
    entrypoint: 'bash'
    args: ['-c', 'set -ex; chmod +x ./gradlew && ./gradlew build --stacktrace --info --no-daemon']
    env:
      - 'GRADLE_USER_HOME=/workspace/.gradle'
      - 'ANDROID_HOME=/opt/android-sdk'
      - 'ANDROID_SDK_ROOT=/opt/android-sdk'
      - 'JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64'
      - 'KEYSTORE_FILE=app/keystore.jks'
      - 'KEYSTORE_PASSWORD=${_KEYSTORE_PASSWORD}'
      - 'KEY_ALIAS=${_KEY_ALIAS}'
      - 'KEY_PASSWORD=${_KEY_PASSWORD}'

  # Run unit tests
  - name: 'docker.io/cirrusci/android-sdk:34'
    entrypoint: 'bash'
    args: ['-c', 'set -ex; ./gradlew test --stacktrace --info --no-daemon']
    env:
      - 'GRADLE_USER_HOME=/workspace/.gradle'
      - 'ANDROID_HOME=/opt/android-sdk'
      - 'ANDROID_SDK_ROOT=/opt/android-sdk'
      - 'JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64'

  # Assemble debug APK
  - name: 'docker.io/cirrusci/android-sdk:34'
    entrypoint: 'bash'
    args: ['-c', 'set -ex; ./gradlew assembleDebug --stacktrace --info --no-daemon']
    env:
      - 'GRADLE_USER_HOME=/workspace/.gradle'
      - 'ANDROID_HOME=/opt/android-sdk'
      - 'ANDROID_SDK_ROOT=/opt/android-sdk'
      - 'JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64'

  # Assemble release APK
  - name: 'docker.io/cirrusci/android-sdk:34'
    entrypoint: 'bash'
    args: ['-c', 'set -ex; ./gradlew assembleRelease --stacktrace --info --no-daemon']
    env:
      - 'GRADLE_USER_HOME=/workspace/.gradle'
      - 'ANDROID_HOME=/opt/android-sdk'
      - 'ANDROID_SDK_ROOT=/opt/android-sdk'
      - 'JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64'
      - 'KEYSTORE_FILE=app/keystore.jks'
      - 'KEYSTORE_PASSWORD=${_KEYSTORE_PASSWORD}'
      - 'KEY_ALIAS=${_KEY_ALIAS}'
      - 'KEY_PASSWORD=${_KEY_PASSWORD}'

  # Upload release APK to Cloud Storage
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'app/build/outputs/apk/release/app-release.apk', 'gs://poc-app-releases/release/app-release-${BUILD_ID}.apk']

  # Clean up keystore
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['rm', 'app/keystore.jks']

# Store the APK as a build artifact
artifacts:
  objects:
    location: 'gs://poc-app-releases/release/'
    paths: ['app-release-${BUILD_ID}.apk']

# Define substitutions
substitutions:
  _KEYSTORE_PASSWORD: '123456'  # Will be set in Cloud Build trigger
  _KEY_ALIAS: 'laennecai-keystore'         # Will be set in Cloud Build trigger
  _KEY_PASSWORD: '123456'      # Will be set in Cloud Build trigger

options:
  logging: CLOUD_LOGGING_ONLY 